import turtle
turtle.shape('turtle')
turtle.color('purple')
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(50)
turtle.exitonclick()
